/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface VerificationResult {
  serverName: string
  verifyingKey: string
  sent: Array<number>
  recv: Array<number>
  time: string
}
export declare function verifyPresentation(json: string): VerificationResult
